import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(new URL('../..', import.meta.url).pathname);
const cfg = JSON.parse(fs.readFileSync(path.join(root, 'system-config/system.config.json'), 'utf8'));
const kebab = (s) => s.replace(/[A-Z]/g, m => '-' + m.toLowerCase());
const out = path.join(root, 'frontend/src/generated');
fs.mkdirSync(out, {recursive:true});

fs.writeFileSync(path.join(out, 'system-config.ts'), 'export const SYSTEM_CONFIG = ' + JSON.stringify(cfg, null, 2) + ' as const;\n');
fs.writeFileSync(path.join(out, 'system-env.ts'), 'export type RuntimeEnv = { API_BASE_URL?: string; TELEGRAM_BOT_USERNAME?: string };\nexport const runtimeEnv: RuntimeEnv = { API_BASE_URL: import.meta.env.VITE_API_BASE_URL, TELEGRAM_BOT_USERNAME: import.meta.env.VITE_TELEGRAM_BOT_USERNAME };\n');
const css = Object.entries(cfg.theme).map(([k,v]) => '  --' + kebab(k) + ': ' + v + ';').join('\n');
fs.writeFileSync(path.join(out, 'system-theme.css'), ':root {\n' + css + '\n}\n');
fs.writeFileSync(path.join(out, 'system-layout.tsx'), 'import type { ReactNode } from \'react\';\nexport function SystemLayout({children}:{children:ReactNode}) { return <div className="system-layout"><main className="system-main">{children}</main><nav className="bottom-action-dock" aria-label="Editor actions"><button>Timeline</button><button>Assets</button><button>Audio</button><button>Export</button></nav></div>; }\n');
const manifest = {name:cfg.system.name,short_name:'AI Studio Pro',start_url:'/',display:'standalone',background_color:cfg.theme.darkBackgroundColor,theme_color:cfg.theme.darkBackgroundColor,icons:[{src:'/logo192.png',sizes:'192x192',type:'image/png'},{src:'/logo512.png',sizes:'512x512',type:'image/png'}]};
fs.writeFileSync(path.join(root,'frontend/public/manifest.json'), JSON.stringify(manifest,null,2));
fs.writeFileSync(path.join(root,'frontend/index.html'), '<!doctype html><html lang="vi"><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"/><title>' + cfg.system.name + '</title><meta name="theme-color" content="' + cfg.theme.darkBackgroundColor + '"/><script src="https://telegram.org/js/telegram-web-app.js"></script></head><body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body></html>');
const workerWrangler = {name:'hendy-video-studio-pro-ai',main:'src/index.ts',compatibility_date:'2026-09-27',vars:{API_BASE_PATH:cfg.network.apiBasePath,CLOUDFLARE_TTS_MODEL:cfg.cloudflareAI.ttsModel},ai:{binding:'AI'},dev:{port:cfg.network.workerPort}};
fs.writeFileSync(path.join(root,'worker/wrangler.jsonc'), JSON.stringify(workerWrangler,null,2));
const backendWrangler = {name:'hendy-video-studio-pro-backend',main:'src/worker.ts',compatibility_date:'2026-09-27',compatibility_flags:['nodejs_compat'],vars:{FRONTEND_ORIGIN:cfg.publicAppUrl,PUBLIC_APP_URL:cfg.publicAppUrl},dev:{port:cfg.network.backendPort}};
fs.writeFileSync(path.join(root,'backend/wrangler.jsonc'), JSON.stringify(backendWrangler,null,2));
const mcpWrangler = {name:'hendy-video-studio-pro-mcp',main:'src/worker.ts',compatibility_date:'2026-09-27',dev:{port:8790}};
fs.writeFileSync(path.join(root,'mcp/cloudflare/wrangler.jsonc'), JSON.stringify(mcpWrangler,null,2));
const botWrangler = {name:'hendy-video-studio-pro-telegram',main:'src/worker.ts',compatibility_date:'2026-09-27',vars:{ADMIN_APP_URL:cfg.publicAppUrl},dev:{port:8791}};
fs.writeFileSync(path.join(root,'example_bot/wrangler.jsonc'), JSON.stringify(botWrangler,null,2));
const rootWrangler = {$schema:'./node_modules/wrangler/config-schema.json',name:'hendy-video-studio-pro',main:'frontend/src/edge.ts',compatibility_date:'2026-09-27',assets:{directory:'./frontend/dist',binding:'ASSETS',not_found_handling:'single-page-application',run_worker_first:['/api/*','/mcp','/telegram/*']},services:[{binding:'BACKEND',service:'hendy-video-studio-pro-backend'},{binding:'AI_EDGE',service:'hendy-video-studio-pro-ai'},{binding:'MCP',service:'hendy-video-studio-pro-mcp'},{binding:'TELEGRAM',service:'hendy-video-studio-pro-telegram'}]};
fs.writeFileSync(path.join(root,'wrangler.jsonc'), JSON.stringify(rootWrangler,null,2));
const workerPackagePath = path.join(root,'worker/package.json');
const workerPackage = JSON.parse(fs.readFileSync(workerPackagePath,'utf8')); workerPackage.devDependencies ??= {}; workerPackage.devDependencies['@cloudflare/workers-types']=cfg.toolchain.workersTypes; workerPackage.devDependencies.wrangler=cfg.toolchain.wrangler; fs.writeFileSync(workerPackagePath,JSON.stringify(workerPackage,null,2)+'\n');
console.log('SOT sync complete: ' + cfg.managedFiles.length + ' managed targets.');
